#!/bin/bash

set -e

mkdir -p /etc/squid3/certs

if [[ -n "$GENERATE_CERTS" ]]; then
	HOST=$(hostname -A | tr -d ' ')
	if ! [ -f "/etc/squid3/certs/${HOST}.crt" ]; then
		sed -i "s|<HOST>|${HOST}|g" /etc/squid3/openssl.cnf
		sed -i "s|<HOST>|${HOST}|g" /etc/squid3/squid.conf
	  /usr/local/bin/mk-certs
	  cat "/etc/squid3/certs/${HOST}.crt"
	fi
fi

chown -R proxy: /etc/squid3/certs
chown -R proxy: /var/cache/squid3
chown -R proxy: /var/log/squid3

/usr/sbin/squid3 -Nz

exec /usr/sbin/squid3 -Nd2
